name: "tpchch"

on:
  push:
    branches:
      - 'release-**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    #The branches below must be a subset of the branches above
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
  schedule:
    - cron:  '30 20 * * *'

  workflow_dispatch:

jobs:
  tpchch:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build linux target
        run: make juicefs

      - name: Run Redis
        run: |
          sudo docker run -d --name redis -v redis-data:/data  \
          -p 6379:6379  redis redis-server --appendonly yes

      - name: Juicefs Format
        run: |
          sudo ./juicefs format redis://127.0.0.1:6379/1 pics

      - name: Juicefs Mount
        run: |
          sudo ./juicefs mount -d redis://127.0.0.1:6379/1 /data/jfs --no-usage-report &

      - name: Install ClickHouse
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates dirmngr
          echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive  apt-get install -y  clickhouse-server clickhouse-client
          

      - name: Change Datadir
        run: |
          sudo chmod 777 /etc/clickhouse-server/config.xml
          sudo sed -i "s?<path>/var/lib/clickhouse/</path>?<path>/jfs/</path>?" /etc/clickhouse-server/config.xml
          cat /etc/clickhouse-server/config.xml
          sudo chmod 777 /var/lib/clickhouse/
          sudo cp -r /var/lib/clickhouse/* /data/jfs/
          sudo chmod -R /data/jfs/*
          ls -l /data/jfs/
          sudo service clickhouse-server start
          sudo service clickhouse-server status


      - name: Gernerate Data
        run: |
          git clone git@github.com:vadimtk/ssb-dbgen.git
          cd ssb-dbgen
          make
          ./dbgen -s 10 -T c
          ./dbgen -s 10 -T l
          ./dbgen -s 10 -T p
          ./dbgen -s 10 -T s
          ./dbgen -s 100 -T d
          ls -lrth
          pwd


      - name: Create Table
        run: |
          echo "hello"


      - name: Import Data
        run: |
          echo "hello"
          clickhouse-client --query "INSERT INTO customer FORMAT CSV" < customer.tbl
          clickhouse-client --query "INSERT INTO part FORMAT CSV" < part.tbl
          clickhouse-client --query "INSERT INTO supplier FORMAT CSV" < supplier.tbl
          clickhouse-client --query "INSERT INTO lineorder FORMAT CSV" < lineorder.tbl


      - name: ClickHouse Test
        run: |
          sudo pip3 install esrally


      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  

      - name: Setup upterm session
        if: ${{ failure() }}
        uses: lhotari/action-upterm@v1